name: CI - Development

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22, 24]
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Instalar dependencias
        run: npm install

      - name: Rodar lint
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: quality
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalar dependencias
        run: npm install

      - name: Gerar artefato
        run: zip -r app.zip .

      - name: Publicar artefato
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: app.zip

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node-version: [22, 24]
    steps:
      - name: Baixar artefato
        uses: actions/download-artifact@v4
        with:
          name: app-build

      - name: Extrair artefato
        run: unzip app.zip

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Instalar dependencias
        run: npm install

      - name: Rodar testes
        run: npm test

      - name: Run Coverage
        run: npm run coverage

  sonar:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalar dependencias
        run: npm install

      - name: Gerar coverage
        run: npm run coverage

      - name: Analise com SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=AllanAleson_aulapipiline2
            -Dsonar.organization=allanaleson
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
